# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8815c6351ccfd1179e0473a109f9d09b3e3b0f1b78847199de6e98e957065f5d1dea2f99b5994600e27c18c4aff97dacd8a7fee420f790bc11079186bea2e6f

test:
  secret_key_base: 45a2ac2d82d5605e6c3e2c4be79ab26bb6c0184ef7344b3774833feaae8736317e36be9d6bfebfc032d34dc0b34da10a7273359a54d0972db483ab32c30fea57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
